// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/poststats/proto/poststats.proto

package poststats

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetPostStatsRequest struct {
	PostUid              string   `protobuf:"bytes,1,opt,name=postUid,proto3" json:"postUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostStatsRequest) Reset()         { *m = GetPostStatsRequest{} }
func (m *GetPostStatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostStatsRequest) ProtoMessage()    {}
func (*GetPostStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47b6d2deeb112c4, []int{0}
}

func (m *GetPostStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostStatsRequest.Unmarshal(m, b)
}
func (m *GetPostStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostStatsRequest.Marshal(b, m, deterministic)
}
func (m *GetPostStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostStatsRequest.Merge(m, src)
}
func (m *GetPostStatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostStatsRequest.Size(m)
}
func (m *GetPostStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostStatsRequest proto.InternalMessageInfo

func (m *GetPostStatsRequest) GetPostUid() string {
	if m != nil {
		return m.PostUid
	}
	return ""
}

type SinglePostStats struct {
	PostUid              string   `protobuf:"bytes,1,opt,name=postUid,proto3" json:"postUid,omitempty"`
	NumLikes             int32    `protobuf:"varint,2,opt,name=numLikes,proto3" json:"numLikes,omitempty"`
	NumDislikes          int32    `protobuf:"varint,3,opt,name=numDislikes,proto3" json:"numDislikes,omitempty"`
	NumViews             int32    `protobuf:"varint,4,opt,name=numViews,proto3" json:"numViews,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SinglePostStats) Reset()         { *m = SinglePostStats{} }
func (m *SinglePostStats) String() string { return proto.CompactTextString(m) }
func (*SinglePostStats) ProtoMessage()    {}
func (*SinglePostStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47b6d2deeb112c4, []int{1}
}

func (m *SinglePostStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SinglePostStats.Unmarshal(m, b)
}
func (m *SinglePostStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SinglePostStats.Marshal(b, m, deterministic)
}
func (m *SinglePostStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SinglePostStats.Merge(m, src)
}
func (m *SinglePostStats) XXX_Size() int {
	return xxx_messageInfo_SinglePostStats.Size(m)
}
func (m *SinglePostStats) XXX_DiscardUnknown() {
	xxx_messageInfo_SinglePostStats.DiscardUnknown(m)
}

var xxx_messageInfo_SinglePostStats proto.InternalMessageInfo

func (m *SinglePostStats) GetPostUid() string {
	if m != nil {
		return m.PostUid
	}
	return ""
}

func (m *SinglePostStats) GetNumLikes() int32 {
	if m != nil {
		return m.NumLikes
	}
	return 0
}

func (m *SinglePostStats) GetNumDislikes() int32 {
	if m != nil {
		return m.NumDislikes
	}
	return 0
}

func (m *SinglePostStats) GetNumViews() int32 {
	if m != nil {
		return m.NumViews
	}
	return 0
}

type CreatePostStatsRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PostUid              string   `protobuf:"bytes,2,opt,name=postUid,proto3" json:"postUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostStatsRequest) Reset()         { *m = CreatePostStatsRequest{} }
func (m *CreatePostStatsRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostStatsRequest) ProtoMessage()    {}
func (*CreatePostStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47b6d2deeb112c4, []int{2}
}

func (m *CreatePostStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostStatsRequest.Unmarshal(m, b)
}
func (m *CreatePostStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostStatsRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostStatsRequest.Merge(m, src)
}
func (m *CreatePostStatsRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostStatsRequest.Size(m)
}
func (m *CreatePostStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostStatsRequest proto.InternalMessageInfo

func (m *CreatePostStatsRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreatePostStatsRequest) GetPostUid() string {
	if m != nil {
		return m.PostUid
	}
	return ""
}

type LikePostRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PostUid              string   `protobuf:"bytes,2,opt,name=postUid,proto3" json:"postUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikePostRequest) Reset()         { *m = LikePostRequest{} }
func (m *LikePostRequest) String() string { return proto.CompactTextString(m) }
func (*LikePostRequest) ProtoMessage()    {}
func (*LikePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47b6d2deeb112c4, []int{3}
}

func (m *LikePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikePostRequest.Unmarshal(m, b)
}
func (m *LikePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikePostRequest.Marshal(b, m, deterministic)
}
func (m *LikePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikePostRequest.Merge(m, src)
}
func (m *LikePostRequest) XXX_Size() int {
	return xxx_messageInfo_LikePostRequest.Size(m)
}
func (m *LikePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LikePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LikePostRequest proto.InternalMessageInfo

func (m *LikePostRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LikePostRequest) GetPostUid() string {
	if m != nil {
		return m.PostUid
	}
	return ""
}

type LikePostResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikePostResponse) Reset()         { *m = LikePostResponse{} }
func (m *LikePostResponse) String() string { return proto.CompactTextString(m) }
func (*LikePostResponse) ProtoMessage()    {}
func (*LikePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47b6d2deeb112c4, []int{4}
}

func (m *LikePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikePostResponse.Unmarshal(m, b)
}
func (m *LikePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikePostResponse.Marshal(b, m, deterministic)
}
func (m *LikePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikePostResponse.Merge(m, src)
}
func (m *LikePostResponse) XXX_Size() int {
	return xxx_messageInfo_LikePostResponse.Size(m)
}
func (m *LikePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LikePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LikePostResponse proto.InternalMessageInfo

type DislikePostRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PostUid              string   `protobuf:"bytes,2,opt,name=postUid,proto3" json:"postUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DislikePostRequest) Reset()         { *m = DislikePostRequest{} }
func (m *DislikePostRequest) String() string { return proto.CompactTextString(m) }
func (*DislikePostRequest) ProtoMessage()    {}
func (*DislikePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47b6d2deeb112c4, []int{5}
}

func (m *DislikePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DislikePostRequest.Unmarshal(m, b)
}
func (m *DislikePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DislikePostRequest.Marshal(b, m, deterministic)
}
func (m *DislikePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DislikePostRequest.Merge(m, src)
}
func (m *DislikePostRequest) XXX_Size() int {
	return xxx_messageInfo_DislikePostRequest.Size(m)
}
func (m *DislikePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DislikePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DislikePostRequest proto.InternalMessageInfo

func (m *DislikePostRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DislikePostRequest) GetPostUid() string {
	if m != nil {
		return m.PostUid
	}
	return ""
}

type DislikePostResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DislikePostResponse) Reset()         { *m = DislikePostResponse{} }
func (m *DislikePostResponse) String() string { return proto.CompactTextString(m) }
func (*DislikePostResponse) ProtoMessage()    {}
func (*DislikePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47b6d2deeb112c4, []int{6}
}

func (m *DislikePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DislikePostResponse.Unmarshal(m, b)
}
func (m *DislikePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DislikePostResponse.Marshal(b, m, deterministic)
}
func (m *DislikePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DislikePostResponse.Merge(m, src)
}
func (m *DislikePostResponse) XXX_Size() int {
	return xxx_messageInfo_DislikePostResponse.Size(m)
}
func (m *DislikePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DislikePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DislikePostResponse proto.InternalMessageInfo

type IncreaseViewsRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PostUid              string   `protobuf:"bytes,2,opt,name=postUid,proto3" json:"postUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncreaseViewsRequest) Reset()         { *m = IncreaseViewsRequest{} }
func (m *IncreaseViewsRequest) String() string { return proto.CompactTextString(m) }
func (*IncreaseViewsRequest) ProtoMessage()    {}
func (*IncreaseViewsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47b6d2deeb112c4, []int{7}
}

func (m *IncreaseViewsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncreaseViewsRequest.Unmarshal(m, b)
}
func (m *IncreaseViewsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncreaseViewsRequest.Marshal(b, m, deterministic)
}
func (m *IncreaseViewsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncreaseViewsRequest.Merge(m, src)
}
func (m *IncreaseViewsRequest) XXX_Size() int {
	return xxx_messageInfo_IncreaseViewsRequest.Size(m)
}
func (m *IncreaseViewsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IncreaseViewsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IncreaseViewsRequest proto.InternalMessageInfo

func (m *IncreaseViewsRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *IncreaseViewsRequest) GetPostUid() string {
	if m != nil {
		return m.PostUid
	}
	return ""
}

type IncreaseViewsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncreaseViewsResponse) Reset()         { *m = IncreaseViewsResponse{} }
func (m *IncreaseViewsResponse) String() string { return proto.CompactTextString(m) }
func (*IncreaseViewsResponse) ProtoMessage()    {}
func (*IncreaseViewsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47b6d2deeb112c4, []int{8}
}

func (m *IncreaseViewsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncreaseViewsResponse.Unmarshal(m, b)
}
func (m *IncreaseViewsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncreaseViewsResponse.Marshal(b, m, deterministic)
}
func (m *IncreaseViewsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncreaseViewsResponse.Merge(m, src)
}
func (m *IncreaseViewsResponse) XXX_Size() int {
	return xxx_messageInfo_IncreaseViewsResponse.Size(m)
}
func (m *IncreaseViewsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IncreaseViewsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IncreaseViewsResponse proto.InternalMessageInfo

type DeletePostStatsRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PostUid              string   `protobuf:"bytes,2,opt,name=postUid,proto3" json:"postUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostStatsRequest) Reset()         { *m = DeletePostStatsRequest{} }
func (m *DeletePostStatsRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePostStatsRequest) ProtoMessage()    {}
func (*DeletePostStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47b6d2deeb112c4, []int{9}
}

func (m *DeletePostStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostStatsRequest.Unmarshal(m, b)
}
func (m *DeletePostStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostStatsRequest.Marshal(b, m, deterministic)
}
func (m *DeletePostStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostStatsRequest.Merge(m, src)
}
func (m *DeletePostStatsRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePostStatsRequest.Size(m)
}
func (m *DeletePostStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostStatsRequest proto.InternalMessageInfo

func (m *DeletePostStatsRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeletePostStatsRequest) GetPostUid() string {
	if m != nil {
		return m.PostUid
	}
	return ""
}

type DeletePostStatsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostStatsResponse) Reset()         { *m = DeletePostStatsResponse{} }
func (m *DeletePostStatsResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePostStatsResponse) ProtoMessage()    {}
func (*DeletePostStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47b6d2deeb112c4, []int{10}
}

func (m *DeletePostStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostStatsResponse.Unmarshal(m, b)
}
func (m *DeletePostStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostStatsResponse.Marshal(b, m, deterministic)
}
func (m *DeletePostStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostStatsResponse.Merge(m, src)
}
func (m *DeletePostStatsResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePostStatsResponse.Size(m)
}
func (m *DeletePostStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostStatsResponse proto.InternalMessageInfo

type GetTokenRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	AppSecret            string   `protobuf:"bytes,2,opt,name=appSecret,proto3" json:"appSecret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenRequest) Reset()         { *m = GetTokenRequest{} }
func (m *GetTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokenRequest) ProtoMessage()    {}
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47b6d2deeb112c4, []int{11}
}

func (m *GetTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenRequest.Unmarshal(m, b)
}
func (m *GetTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenRequest.Merge(m, src)
}
func (m *GetTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokenRequest.Size(m)
}
func (m *GetTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenRequest proto.InternalMessageInfo

func (m *GetTokenRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *GetTokenRequest) GetAppSecret() string {
	if m != nil {
		return m.AppSecret
	}
	return ""
}

type GetTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenResponse) Reset()         { *m = GetTokenResponse{} }
func (m *GetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokenResponse) ProtoMessage()    {}
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a47b6d2deeb112c4, []int{12}
}

func (m *GetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenResponse.Unmarshal(m, b)
}
func (m *GetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenResponse.Merge(m, src)
}
func (m *GetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokenResponse.Size(m)
}
func (m *GetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenResponse proto.InternalMessageInfo

func (m *GetTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*GetPostStatsRequest)(nil), "poststats.GetPostStatsRequest")
	proto.RegisterType((*SinglePostStats)(nil), "poststats.SinglePostStats")
	proto.RegisterType((*CreatePostStatsRequest)(nil), "poststats.CreatePostStatsRequest")
	proto.RegisterType((*LikePostRequest)(nil), "poststats.LikePostRequest")
	proto.RegisterType((*LikePostResponse)(nil), "poststats.LikePostResponse")
	proto.RegisterType((*DislikePostRequest)(nil), "poststats.DislikePostRequest")
	proto.RegisterType((*DislikePostResponse)(nil), "poststats.DislikePostResponse")
	proto.RegisterType((*IncreaseViewsRequest)(nil), "poststats.IncreaseViewsRequest")
	proto.RegisterType((*IncreaseViewsResponse)(nil), "poststats.IncreaseViewsResponse")
	proto.RegisterType((*DeletePostStatsRequest)(nil), "poststats.DeletePostStatsRequest")
	proto.RegisterType((*DeletePostStatsResponse)(nil), "poststats.DeletePostStatsResponse")
	proto.RegisterType((*GetTokenRequest)(nil), "poststats.GetTokenRequest")
	proto.RegisterType((*GetTokenResponse)(nil), "poststats.GetTokenResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostStatsClient is the client API for PostStats service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostStatsClient interface {
	GetPostStats(ctx context.Context, in *GetPostStatsRequest, opts ...grpc.CallOption) (*SinglePostStats, error)
	CreatePostStats(ctx context.Context, in *CreatePostStatsRequest, opts ...grpc.CallOption) (*SinglePostStats, error)
	LikePost(ctx context.Context, in *LikePostRequest, opts ...grpc.CallOption) (*LikePostResponse, error)
	DislikePost(ctx context.Context, in *DislikePostRequest, opts ...grpc.CallOption) (*DislikePostResponse, error)
	IncreaseViews(ctx context.Context, in *IncreaseViewsRequest, opts ...grpc.CallOption) (*IncreaseViewsResponse, error)
	DeletePostStats(ctx context.Context, in *DeletePostStatsRequest, opts ...grpc.CallOption) (*DeletePostStatsResponse, error)
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error)
}

type postStatsClient struct {
	cc *grpc.ClientConn
}

func NewPostStatsClient(cc *grpc.ClientConn) PostStatsClient {
	return &postStatsClient{cc}
}

func (c *postStatsClient) GetPostStats(ctx context.Context, in *GetPostStatsRequest, opts ...grpc.CallOption) (*SinglePostStats, error) {
	out := new(SinglePostStats)
	err := c.cc.Invoke(ctx, "/poststats.PostStats/GetPostStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postStatsClient) CreatePostStats(ctx context.Context, in *CreatePostStatsRequest, opts ...grpc.CallOption) (*SinglePostStats, error) {
	out := new(SinglePostStats)
	err := c.cc.Invoke(ctx, "/poststats.PostStats/CreatePostStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postStatsClient) LikePost(ctx context.Context, in *LikePostRequest, opts ...grpc.CallOption) (*LikePostResponse, error) {
	out := new(LikePostResponse)
	err := c.cc.Invoke(ctx, "/poststats.PostStats/LikePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postStatsClient) DislikePost(ctx context.Context, in *DislikePostRequest, opts ...grpc.CallOption) (*DislikePostResponse, error) {
	out := new(DislikePostResponse)
	err := c.cc.Invoke(ctx, "/poststats.PostStats/DislikePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postStatsClient) IncreaseViews(ctx context.Context, in *IncreaseViewsRequest, opts ...grpc.CallOption) (*IncreaseViewsResponse, error) {
	out := new(IncreaseViewsResponse)
	err := c.cc.Invoke(ctx, "/poststats.PostStats/IncreaseViews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postStatsClient) DeletePostStats(ctx context.Context, in *DeletePostStatsRequest, opts ...grpc.CallOption) (*DeletePostStatsResponse, error) {
	out := new(DeletePostStatsResponse)
	err := c.cc.Invoke(ctx, "/poststats.PostStats/DeletePostStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postStatsClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	out := new(GetTokenResponse)
	err := c.cc.Invoke(ctx, "/poststats.PostStats/GetToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostStatsServer is the server API for PostStats service.
type PostStatsServer interface {
	GetPostStats(context.Context, *GetPostStatsRequest) (*SinglePostStats, error)
	CreatePostStats(context.Context, *CreatePostStatsRequest) (*SinglePostStats, error)
	LikePost(context.Context, *LikePostRequest) (*LikePostResponse, error)
	DislikePost(context.Context, *DislikePostRequest) (*DislikePostResponse, error)
	IncreaseViews(context.Context, *IncreaseViewsRequest) (*IncreaseViewsResponse, error)
	DeletePostStats(context.Context, *DeletePostStatsRequest) (*DeletePostStatsResponse, error)
	GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error)
}

func RegisterPostStatsServer(s *grpc.Server, srv PostStatsServer) {
	s.RegisterService(&_PostStats_serviceDesc, srv)
}

func _PostStats_GetPostStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostStatsServer).GetPostStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poststats.PostStats/GetPostStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostStatsServer).GetPostStats(ctx, req.(*GetPostStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostStats_CreatePostStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostStatsServer).CreatePostStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poststats.PostStats/CreatePostStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostStatsServer).CreatePostStats(ctx, req.(*CreatePostStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostStats_LikePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostStatsServer).LikePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poststats.PostStats/LikePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostStatsServer).LikePost(ctx, req.(*LikePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostStats_DislikePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DislikePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostStatsServer).DislikePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poststats.PostStats/DislikePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostStatsServer).DislikePost(ctx, req.(*DislikePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostStats_IncreaseViews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncreaseViewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostStatsServer).IncreaseViews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poststats.PostStats/IncreaseViews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostStatsServer).IncreaseViews(ctx, req.(*IncreaseViewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostStats_DeletePostStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostStatsServer).DeletePostStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poststats.PostStats/DeletePostStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostStatsServer).DeletePostStats(ctx, req.(*DeletePostStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostStats_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostStatsServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/poststats.PostStats/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostStatsServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostStats_serviceDesc = grpc.ServiceDesc{
	ServiceName: "poststats.PostStats",
	HandlerType: (*PostStatsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPostStats",
			Handler:    _PostStats_GetPostStats_Handler,
		},
		{
			MethodName: "CreatePostStats",
			Handler:    _PostStats_CreatePostStats_Handler,
		},
		{
			MethodName: "LikePost",
			Handler:    _PostStats_LikePost_Handler,
		},
		{
			MethodName: "DislikePost",
			Handler:    _PostStats_DislikePost_Handler,
		},
		{
			MethodName: "IncreaseViews",
			Handler:    _PostStats_IncreaseViews_Handler,
		},
		{
			MethodName: "DeletePostStats",
			Handler:    _PostStats_DeletePostStats_Handler,
		},
		{
			MethodName: "GetToken",
			Handler:    _PostStats_GetToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/poststats/proto/poststats.proto",
}

func init() {
	proto.RegisterFile("pkg/poststats/proto/poststats.proto", fileDescriptor_a47b6d2deeb112c4)
}

var fileDescriptor_a47b6d2deeb112c4 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcd, 0x6e, 0xda, 0x40,
	0x10, 0x80, 0x65, 0x0a, 0x2d, 0x1e, 0x5a, 0x19, 0x2d, 0x7f, 0xae, 0xdb, 0x52, 0xd7, 0xbd, 0x70,
	0x02, 0xa9, 0x7d, 0x82, 0x08, 0x12, 0x20, 0xe2, 0x80, 0x4c, 0x12, 0xe5, 0xea, 0x90, 0x11, 0xb2,
	0x00, 0x7b, 0xe3, 0x5d, 0x94, 0x27, 0xc8, 0xf3, 0xe4, 0x15, 0x23, 0x9b, 0xb5, 0xbd, 0x36, 0x86,
	0x03, 0xc9, 0x71, 0x76, 0x66, 0x3e, 0xcf, 0x8e, 0xbe, 0x35, 0xfc, 0xa5, 0xeb, 0xd5, 0x80, 0xfa,
	0x8c, 0x33, 0xee, 0x70, 0x36, 0xa0, 0x81, 0xcf, 0xfd, 0x34, 0xee, 0x47, 0x31, 0x51, 0x93, 0x03,
	0x6b, 0x00, 0x8d, 0x31, 0xf2, 0xb9, 0xcf, 0xf8, 0x22, 0x8c, 0x6d, 0x7c, 0xda, 0x21, 0xe3, 0x44,
	0x87, 0x2f, 0x61, 0xcd, 0xad, 0xfb, 0xa8, 0x2b, 0xa6, 0xd2, 0x53, 0xed, 0x38, 0xb4, 0x5e, 0x14,
	0xd0, 0x16, 0xae, 0xb7, 0xda, 0x60, 0xd2, 0x74, 0xbc, 0x9a, 0x18, 0x50, 0xf5, 0x76, 0xdb, 0x99,
	0xbb, 0x46, 0xa6, 0x97, 0x4c, 0xa5, 0x57, 0xb1, 0x93, 0x98, 0x98, 0x50, 0xf3, 0x76, 0xdb, 0x91,
	0xcb, 0x36, 0x51, 0xfa, 0x53, 0x94, 0x96, 0x8f, 0x44, 0xf7, 0x9d, 0x8b, 0xcf, 0x4c, 0x2f, 0x27,
	0xdd, 0x51, 0x6c, 0x4d, 0xa0, 0x3d, 0x0c, 0xd0, 0xe1, 0x78, 0x30, 0x7b, 0x13, 0x2a, 0xdc, 0x5f,
	0xa3, 0x27, 0x66, 0xd9, 0x07, 0xf2, 0x8c, 0xa5, 0xec, 0x8d, 0x2e, 0x40, 0x0b, 0x07, 0x0a, 0x39,
	0xe7, 0x22, 0x08, 0xd4, 0x53, 0x04, 0xa3, 0xbe, 0xc7, 0xd0, 0x1a, 0x01, 0x11, 0x17, 0x79, 0x0f,
	0xb9, 0x05, 0x8d, 0x0c, 0x45, 0xc0, 0xaf, 0xa0, 0x39, 0xf5, 0x96, 0x01, 0x3a, 0x0c, 0xa3, 0x75,
	0x9c, 0x8b, 0xef, 0x40, 0x2b, 0xc7, 0x11, 0x1f, 0x98, 0x40, 0x7b, 0x84, 0x1b, 0xfc, 0x80, 0xf5,
	0x7e, 0x87, 0xce, 0x01, 0x49, 0x7c, 0xe4, 0x12, 0xb4, 0x31, 0xf2, 0x9b, 0x10, 0x20, 0xd1, 0x1d,
	0x4a, 0xa7, 0xb1, 0x48, 0xfb, 0x80, 0xfc, 0x04, 0xd5, 0xa1, 0x74, 0x81, 0xcb, 0x00, 0xb9, 0xe0,
	0xa7, 0x07, 0x56, 0x0f, 0xea, 0x29, 0x66, 0x8f, 0x2e, 0x9e, 0xf2, 0xdf, 0x6b, 0x19, 0xd4, 0x54,
	0xdb, 0x6b, 0xf8, 0x2a, 0xbb, 0x4f, 0xba, 0xfd, 0xf4, 0xa1, 0x14, 0x3c, 0x0a, 0xc3, 0x90, 0xf2,
	0xf9, 0x27, 0x30, 0x07, 0x2d, 0xa7, 0x23, 0xf9, 0x23, 0x95, 0x17, 0xab, 0x7a, 0x92, 0x38, 0x84,
	0x6a, 0xec, 0x14, 0x91, 0xeb, 0x72, 0xae, 0x1a, 0x3f, 0x0a, 0x73, 0x62, 0x0d, 0x33, 0xa8, 0x49,
	0xfa, 0x90, 0x5f, 0x52, 0xed, 0xa1, 0x9c, 0x46, 0xf7, 0x58, 0x5a, 0xd0, 0x6c, 0xf8, 0x96, 0xb1,
	0x85, 0xfc, 0x96, 0x1a, 0x8a, 0x7c, 0x34, 0xcc, 0xe3, 0x05, 0x82, 0x79, 0x0f, 0x5a, 0x4e, 0x8f,
	0xcc, 0xe2, 0x8a, 0x25, 0x34, 0xac, 0x53, 0x25, 0x82, 0x3c, 0x84, 0x6a, 0xac, 0x45, 0x66, 0x81,
	0x39, 0xe5, 0x32, 0x0b, 0xcc, 0x7b, 0xf4, 0xf0, 0x39, 0xfa, 0x63, 0xfe, 0x7f, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0x05, 0xbc, 0x76, 0xf8, 0x58, 0x05, 0x00, 0x00,
}
